# Generated by Django 4.2.5 on 2023-09-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id_filme', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('genero', models.TextField(max_length=50)),
                ('ano_lancamento', models.IntegerField()),
                ('Sinopse', models.TextField(max_length=250)),
                ('capa', models.URLField()),
            ],
        ),
    ]
